spring:
  datasource:
    jpadbinfo:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      driver-class-name: org.postgresql.Driver
      username: parkhj
      password: parkhj
      connection-test-query: SELECT * from users
    somedb2:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      driver-class-name: org.postgresql.Driver
      username: parkhj
      password: parkhj
      connection-test-query: SELECT * from users
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: auto
#    hibernate:
#      dialec: org.hibernate.dialect.PostgreSQL94Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE